name: google_maps_api_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  auto_route: 3.2.0
  cupertino_icons: ^1.0.2
  easy_localization: 3.0.0
  flutter_bloc: 8.0.0
  flutter_native_splash: 1.3.2
  flutter_screenutil: 5.0.1+1
  get_it: 7.2.0
  hive_flutter: 1.1.0
  http: 0.13.4
  shimmer: 2.0.0
  google_maps_flutter: 2.1.1
  custom_info_window: 1.0.1
  flutter_config: 2.0.0
  clippy_flutter: 2.0.0-nullsafety.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 3.2.0
  build_runner: 2.1.5
  flutter_launcher_icons: 0.9.2
  flutter_lints: 1.0.0
  freezed: 0.14.5
  hive_generator: 1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/map/
    - assets/images/
flutter_native_splash:
  color: "#212121"
  image: "assets/images/splash.png"

flutter_icons:
  image_path: "assets/images/favicon.png"
  android: true
  ios: true
  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
